{
 "title": "k6_nt Copy",
 "time": { "from": "2025-11-03T13:02:08.622Z", "to": "2025-11-03T13:06:34.480Z" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Active Virtual Users (VUs)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "Time", "id": "2", "settings": { "interval": "1s" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Value", "id": "1", "type": "sum" }
     ],
     "query": "MetricName:vus",
     "timeField": "Time"
    }
   ]
  },
  {
   "title": "Requests per Second (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 5, "x": 7, "y": 0 },
   "targets": [
    {
     "alias": "Requests per Second",
     "bucketAggs": [
      { "field": "Time", "id": "2", "settings": { "interval": "1s" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Value", "id": "1", "type": "sum" }
     ],
     "query": "MetricName:http_reqs",
     "timeField": "Time"
    }
   ]
  },
  {
   "title": "[POST] URLs Success",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Tags.name",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      },
      {
       "field": "Tags.method",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "Value", "id": "1", "type": "min" },
      { "field": "Value", "id": "3", "type": "max" },
      { "field": "Value", "id": "4", "type": "avg" },
      { "field": "Value", "id": "5", "settings": { "percents": [ "90" ] }, "type": "percentiles" },
      { "field": "Value", "id": "6", "settings": { "percents": [ "95" ] }, "type": "percentiles" }
     ],
     "query": "MetricName: http_req_duration AND Tags.method:POST AND NOT Tags.status:(502 OR 403 OR 500 OR 400 OR 0 OR 302 OR 504) AND NOT Tags.name:/callback/",
     "timeField": "Time"
    }
   ]
  },
  {
   "title": "[GET] URLs Success",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Tags.name",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      },
      {
       "field": "Tags.method",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "Value", "id": "1", "type": "min" },
      { "field": "Value", "id": "4", "type": "max" },
      { "field": "Value", "id": "5", "type": "avg" },
      { "field": "Value", "id": "6", "settings": { "percents": [ "90" ] }, "type": "percentiles" },
      { "field": "Value", "id": "7", "settings": { "percents": [ "95" ] }, "type": "percentiles" }
     ],
     "query": "MetricName: http_req_duration AND Tags.method:GET AND NOT Tags.status:(502 OR 403 OR 500 OR 400 OR 0 OR 302 OR 504) AND NOT Tags.name:/callback/",
     "timeField": "Time"
    }
   ]
  },
  {
   "title": "Success/Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Errors",
     "bucketAggs": [
      { "field": "Time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "MetricName", "id": "1", "type": "count" }
     ],
     "query": "MetricName:http_req_failed AND (NOT Tags.status:(301 OR 302 OR 303 OR 200 OR 401) AND NOT Tags.name:/callback/)"
    },
    {
     "alias": "Success",
     "bucketAggs": [
      { "field": "Time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "MetricName", "id": "1", "type": "count" }
     ],
     "query": "MetricName:http_req_failed AND (Tags.status:(301 OR 302 OR 303 OR 200 OR 0) AND NOT Tags.name:/callback/)"
    }
   ]
  },
  {
   "title": "Failed URLs and latency",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Tags.name",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      },
      {
       "field": "Tags.method",
       "id": "8",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "Value", "id": "1", "type": "max" },
      { "field": "Value", "id": "3", "type": "min" },
      { "field": "Value", "id": "4", "type": "avg" },
      { "field": "Value", "id": "5", "settings": { "percents": [ "90" ] }, "type": "percentiles" },
      { "field": "Value", "id": "7", "settings": { "percents": [ "95" ] }, "type": "percentiles" }
     ],
     "query": "MetricName: http_req_duration AND NOT Tags.status:(301 OR 302 OR 303 OR 200) AND NOT Tags.name:/callback/",
     "timeField": "Time"
    }
   ]
  },
  {
   "title": "URLs and latency",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Tags.method",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      },
      {
       "field": "Tags.status",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "Value", "id": "1", "type": "min" },
      { "field": "Value", "id": "3", "type": "max" },
      { "field": "Value", "id": "4", "type": "avg" },
      { "field": "Value", "id": "5", "settings": { "percents": [ "90" ] }, "type": "percentiles" },
      { "field": "Value", "id": "6", "settings": { "percents": [ "95" ] }, "type": "percentiles" }
     ],
     "query": "MetricName:http_req_duration AND NOT Tags.status:(502 OR 403 OR 500 OR 400 OR 0 OR 504) AND NOT Tags.name:/callback/",
     "timeField": "Time"
    }
   ]
  }
 ]
}